app:
    aws:
        cognito:
            pool-id :  eu-west-1
            fed-pool-id : eu-west-1
            client-id :
            region: eu-west-1
            domain-name :

spring:
  output:
    ansi:
      enabled: "ALWAYS"
  main:
    banner-mode: "OFF"
