micronaut:
  application:
    name: mn-cli-cognito

app:
  aws:
    cognito:
      pool-id :  eu-west-1_gVkypexZ5
      fed-pool-id : eu-west-1
      client-id : 1242pkpdpd6omkldubs41qo18j
      region : eu-west-1
      domain-name :
